# Generated by Django 3.2.14 on 2022-08-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT_APP', '0003_auto_20220803_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='placeholder', upload_to='static/images/'),
        ),
    ]
