# Generated by Django 3.2.14 on 2022-11-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PT_APP', '0007_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
